name: Create the DEB

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Copy script files around to stop .github from being added to the package then build the package
        run: |
          dpkg-deb --build ./pipeLog_0_0_amd64/ 

      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: pipeLog_0_0_amd64.deb.deb